name: Python CI/CD

on:
  push:
    branches: [ master ]

jobs:
  # ---------- Линтер ----------
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Create venv (with fallback)
        run: |
          python3 --version
          python3 -m venv .venv || (python3 -m pip install --user virtualenv && ~/.local/bin/virtualenv .venv)
          . .venv/bin/activate
          python -m pip install -U pip
          python -m pip install flake8

      - name: Run linter
        run: .venv/bin/flake8 app/ tests/

  # ---------- Тесты ----------
  test:
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Create venv (with fallback)
        run: |
          python3 --version
          python3 -m venv .venv || (python3 -m pip install --user virtualenv && ~/.local/bin/virtualenv .venv)
          . .venv/bin/activate
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install -U pytest

      - name: Expose repo root on PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Run tests
        run: .venv/bin/pytest --maxfail=1 --disable-warnings -q


  # ---------- Сборка Docker ----------
  build-docker:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image (no cache)
        run: |
          docker builder prune -f || true
          docker system prune -af || true
          docker build --no-cache -t TPO-lab3:latest .

  # ---------- Деплой ----------
  deploy:
    runs-on: self-hosted
    needs: build-docker
    steps:
      - name: Deploy Docker container
        run: |
          docker stop TPO-lab3 || true
          docker rm TPO-lab3 || true
          docker run -d --name TPO-lab3 -p 8000:8000 TPO-lab3:latest
