name: Python CI/CD

on:
  push:
    branches: [ master ]

jobs:
  # ---------- Линтер ----------
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python for lint
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # можно 3.12, но 3.11 быстрее ставится

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8

      - name: Run linter
        run: flake8 app/ tests/

  # ---------- Тесты ----------
  test:
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python for tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          # гарантируем pytest, если его нет в requirements.txt
          python -m pip install -U pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  # ---------- Сборка Docker ----------
  build-docker:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image (no cache)
        run: |
          docker builder prune -f || true
          docker system prune -af || true
          docker build --no-cache -t TPO-lab3:latest .

  # ---------- Деплой ----------
  deploy:
    runs-on: self-hosted
    needs: build-docker
    steps:
      - name: Deploy Docker container
        run: |
          docker stop TPO-lab3 || true
          docker rm TPO-lab3 || true
          docker run -d --name TPO-lab3 -p 8000:8000 TPO-lab3:latest
